# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizzbuzz', '0002_auto_20171120_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='default_code',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
